version: 2.1

aliases:
  - &docker_auth
    auth:
      username: ${DOCKER_USER}
      password: ${DOCKER_PASS}

  - &default-context
    context:
      - shared-creds

executors:
  default-executor:
    docker:
      - image: opuscapita/minsk-core-ci:4
        <<: *docker_auth
    working_directory: ~/build

  machine-user-executor:
    docker:
      - image: opuscapita/minsk-core-machineuser-env:2
        <<: *docker_auth

orbs:
  jira: circleci/jira@2.0

jobs:
  init:
    executor: machine-user-executor
    steps:
      - run: generate_bash_env_exports.sh GH_MAIL GH_NAME CIRCLE_CI_TOKEN > ~/generated_bash_env
      - persist_to_workspace:
          root: ~/
          paths:
            - generated_bash_env

  build:
    executor: default-executor
    steps:
      - attach_workspace:
          at: /workspace
      - run: cat /workspace/generated_bash_env >> $BASH_ENV

      - checkout
      - restore_cache:
          keys:
            - styles-{{ .Branch }}-{{ checksum "package.json" }}
            - styles-{{ .Branch }}
            - styles
      - run: if [ -f /.dockerenv ]; then configure-maven.sh && configure-grails.sh && configure-npm.sh; fi
      - run:
          name: "Installing dependencies."
          command: yarn install
      - save_cache:
          key: styles-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
              - ./node_modules
              - ./yarn.lock
      - run:
          name: "Running lint."
          command: npm start lint
      - run:
          name: Deploy snapshot.
          command: npm start grails-plugin-deploy-snapshot

  update-gh-pages:
    executor: default-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - styles-{{ .Branch }}-{{ checksum "package.json" }}
            - styles-{{ .Branch }}
            - styles
      - run: if [ -f /.dockerenv ]; then configure-maven.sh && configure-grails.sh && configure-npm.sh; fi
      - run:
          name: "Installing dependencies."
          command: yarn install
      - save_cache:
          key: styles-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
              - ./node_modules
              - ./yarn.lock
      - run:
          name: build-gh-pages
          command: ./scripts/gh-pages/build.sh
      - run:
          name: deploy-gh-pages
          command: ./scripts/gh-pages/deploy.sh .gh-pages-tmp

  build_release:
    executor: default-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-styles-{{ .Branch }}-{{ checksum "package.json" }}'
            - 'v1-styles-{{ .Branch }}'
            - v1-styles
      - run: if [ -f /.dockerenv ]; then configure-maven.sh && configure-grails.sh && configure-npm.sh; fi
      - run:
          name: Installing dependencies.
          command: yarn install
      - save_cache:
          key: 'v1-styles-{{ .Branch }}-{{ checksum "package.json" }}'
          paths:
            - ./node_modules
            - ./yarn.lock
            - ~/.m2/repository
      - run:
          name: Running lint.
          command: npm start lint
      - run:
          name: Deploy.
          command: npm start publish-release

  release:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Executing release scrtipt.
          command: .circleci/release.sh

workflows:
  release-and-build:
    jobs:
      - init:
          <<: *default-context
          filters:
            tags:
              only: /.*/
      - release:
          <<: *default-context
          filters:
            branches:
              only: release
          requires:
            - init
          post-steps:
            - jira/notify:
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>
      - build:
          <<: *default-context
          filters:
            branches:
              ignore:
                - gh-pages
                - release
          requires:
            - init
          post-steps:
            - jira/notify:
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>
      - update-gh-pages:
          <<: *default-context
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - build_release:
          <<: *default-context
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - init
          post-steps:
            - jira/notify:
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>
